{"ast":null,"code":"import _regeneratorRuntime from \"/github/workspace/node_modules/next/node_modules/@babel/runtime/regenerator\";\nimport _asyncToGenerator from \"/github/workspace/node_modules/next/node_modules/@babel/runtime/helpers/esm/asyncToGenerator\";\nimport { message } from '@/components/notification';\nimport axios from 'axios'; // 超时时间 15 秒\n\naxios.defaults.timeout = 15 * 1000;\nexport var backendURI = !!process.env['backendURI'] || 'http://127.0.0.1:50000';\n\nfunction parseURL(url) {\n  return backendURI + url;\n} // export const requestAsync = async (method: 'post' | 'get', url: string, data: any) => {\n//   var r = await axios({\n//     method: method,\n//     url: parseURL(url),\n//     params: data,\n//   });\n//   return r.data;\n// };\n// export const requestCallback = (\n//   method: 'post' | 'get',\n//   url: string,\n//   data: any,\n//     callback: (data: any) => void,\n//   ignore_exception?:boolean,\n// ) => {\n//   axios({\n//     method: method,\n//     url: parseURL(url),\n//     params: data,\n//   })\n//     .then((data) => data.data)\n//     .then((data) => callback(data))\n//     .catch((err) => console.log(err));\n// };\n\n\nexport var request = /*#__PURE__*/function () {\n  var _ref = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime.mark(function _callee(method, url, data, callback, ignore_exception) {\n    var r;\n    return _regeneratorRuntime.wrap(function _callee$(_context) {\n      while (1) {\n        switch (_context.prev = _context.next) {\n          case 0:\n            ignore_exception = typeof ignore_exception === 'undefined' ? false : ignore_exception;\n            _context.prev = 1;\n            _context.next = 4;\n            return axios({\n              method: method,\n              url: parseURL(url),\n              params: method === 'get' ? data : undefined,\n              data: method === 'post' ? data : undefined,\n              withCredentials: true\n            });\n\n          case 4:\n            r = _context.sent;\n            _context.next = 13;\n            break;\n\n          case 7:\n            _context.prev = 7;\n            _context.t0 = _context[\"catch\"](1);\n            console.log(_context.t0);\n\n            if (ignore_exception) {\n              _context.next = 13;\n              break;\n            }\n\n            if (typeof document !== 'undefined') message({\n              title: '请求发生错误',\n              content: \"\".concat(_context.t0),\n              alertType: 'error'\n            });\n            throw _context.t0;\n\n          case 13:\n            if (!!callback) {\n              callback(r.data);\n            }\n\n            return _context.abrupt(\"return\", r.data);\n\n          case 15:\n          case \"end\":\n            return _context.stop();\n        }\n      }\n    }, _callee, null, [[1, 7]]);\n  }));\n\n  return function request(_x, _x2, _x3, _x4, _x5) {\n    return _ref.apply(this, arguments);\n  };\n}();","map":null,"metadata":{},"sourceType":"module"}